### PR TITLE
LOGIC: Like and unlike post by postId

### PR DESCRIPTION
**Pull request by alpha037**
### Implemented the following logic:

- [x] Like post by postId
like-post-by-postId

- [x] Cannot like already liked post
cannot-like-already-liked-post

- [x] Unlike post by postId
unlike-post-by-postId

- [x] Cannot unlike already unliked post
cannot-unlike-already-unliked-post

### CODE REVIEW

**Comment by alpha037** [comment]
@championswimmer, hey, any idea why the test suites are failing?

**Comment by alpha037** [comment]
@championswimmer, it's resolved now. Turns out I didn't create a separate test suite for `Likes`. 🤦🏼

**Comment by championswimmer** [comment]
Hey @alpha037 you will have refactor this a bit, I just updated the project to nestjs 8.0, so there are slight changes in the testing mocks

**Comment by alpha037** [comment]
Oh, okay! I'll refactor this soon. :)

**Review by championswimmer — APPROVED** [review]

**Comment by championswimmer** [comment]
Looks good! Thanks

**Pull request merged**
